// <auto-generated />
namespace Marfrig.CompraGado.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Types));
        
        string IMigrationMetadata.Id
        {
            get { return "201812062026526_Types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
